# Generated by Django 5.2.10 on 2026-02-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_teachers_user_alter_teachers_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeapp.course'),
        ),
    ]
